### PR TITLE
ODC-7394,ODC-7406: Create Pipeline Metrics page which use Tekton Results API & Make the Pipeline overview page responsive

### PR DESCRIPTION
**Pull request by Lucifergene**
**Fixes**: 
https://issues.redhat.com/browse/ODC-7394
https://issues.redhat.com/browse/ODC-7406

**Solution Description**: 

- [x] Added the Metrics page UI
- [x] Made the Overview page responsive

**Screen shots / Gifs for design review**: 

**Overview Page:**

https://github.com/openshift-pipelines/console-plugin/assets/47265560/9d034290-1e06-4c0f-bbed-56a40b25c870

**Metrics Page:**

https://github.com/openshift-pipelines/console-plugin/assets/47265560/737a887a-f9d2-4909-b45b-971fe16f2265

**Unit test coverage report**: 
None

**Test setup:**
1. Install Pipelines operator & [Tekton Results](https://gist.github.com/vikram-raj/257d672a38eb2159b0368eaed8f8970a)
2. Create a Pipeline

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by vikram-raj — COMMENTED** [review]
The chart get overflow from the card

image

**Comment by Lucifergene** [comment]
@vikram-raj The issue has been resolved. Please review :)

**Review by jerolimov — APPROVED** [review]
Lgtm! Let us merge this an continue based on that.

**Pull request merged**
