### PR TITLE
SRVKP-6629: Pipelines : many i18n misses

### PR DESCRIPTION
**Pull request by lokanandaprabhu**
**Fixes:**
https://issues.redhat.com/browse/SRVKP-6629

**Description:**
Added the scripts which helps in translation and added the missing translations

### CODE REVIEW

**Comment by vikram-raj** [comment]
It looks like you miss to add `yarn.lock` file to this PR.

**Comment by lokanandaprabhu** [comment]
Added `yarn.lock`  file

**Review by vikram-raj — COMMENTED** [review]
/lgtm

**Comment by vikram-raj** [comment]
/close

closing this in favour of https://github.com/openshift-pipelines/console-plugin/pull/169

**Pull request closed without merging**
